CATEGORY_MAP = {
    "Income": [
        "Kelly 1st Paycheck",
        "Kelly 2nd Paycheck",
        "Matt 1st Pay Check",
        "Matt 2nd Paycheck",
        "Cell Phone Reimbursement",
        "Misc",
    ],
    "Savings": [
        "Yearly Taxes",
        "Christmas  Presents",
        "Vacation Fund",
        "Emergency Fund",
        "Birthday Lexie",
        "Birthday Matt",
        "Birthday Kelly",
        "Birthday Scott",
        "Birthday Olivia",
        "Misc Savings (Extra)",
    ],
    "Variable Expenses": [
        "Groceries",
        "Restaurants",
        "Kids Sports",
        "Medical",
        "Entertainment",
        "Home Expenses",
        "Shopping",
        "Gas",
        "Donations",
        "Dog Expenses",
        "Car Expenses",
        "Kids School Supplies",
        "Spa/Aesthetics/Nails",
        "Work Expenses",
        "Travel",
        "Taxes",
    ],
    "Monthly Bills": [
        "Mortgage",
        "Water/Sewer",
        "Gas/ Peidmont",
        "Electric/ Duke",
        "Life Insurance -Matt",
        "Life Insurance - Kelly",
        "Chevy",
        "Geico",
        "Audi",
        "Internet AT&T",
        "Verizon",
        "Thorne (Niacel + Probiotic)",
        "ChatGPT",
        "Salon Out",
        "Salon In",
        "Rocket Money",
        "Spotify",
        "Matt Rent",
        "Utilities",
        "Boat Club (Wells Fargo)",
    ],
    "Non-Monthly Bills": [
        "Progesterone",
        "Advanced Labs",
        "HOA",
        "Tirzepatide",
        "Botox",
        "Skylight Calendar",
        "Greenlight Transfers",
        "Calm App - Apple",
    ],
    "Debt": [
        "Bank of America Visa",
        "Citi Bank",
        "Wells Fargo Visa",
        "Lowes",
        "Best Egg",
        "Wells Fargo Reflect",
        "Ameris Bank Loan",
        "Heloc",
    ],
}


CATEGORY_TYPES = list(CATEGORY_MAP.keys())

